// Top affluent cities/areas for prospecting high-end service businesses
// UK: 100 cities | US: 200 cities | Canada: 85 cities (most affluent metro areas)

export interface CityData {
  name: string;
  region: string;
  country: 'United Kingdom' | 'United States' | 'Canada';
}

export const UK_AFFLUENT_CITIES: CityData[] = [
  // London Boroughs & Surrounding
  { name: 'Kensington', region: 'London', country: 'United Kingdom' },
  { name: 'Chelsea', region: 'London', country: 'United Kingdom' },
  { name: 'Mayfair', region: 'London', country: 'United Kingdom' },
  { name: 'Knightsbridge', region: 'London', country: 'United Kingdom' },
  { name: 'Belgravia', region: 'London', country: 'United Kingdom' },
  { name: 'Hampstead', region: 'London', country: 'United Kingdom' },
  { name: 'Notting Hill', region: 'London', country: 'United Kingdom' },
  { name: 'Fulham', region: 'London', country: 'United Kingdom' },
  { name: 'Richmond', region: 'London', country: 'United Kingdom' },
  { name: 'Wimbledon', region: 'London', country: 'United Kingdom' },
  { name: 'Chiswick', region: 'London', country: 'United Kingdom' },
  { name: 'St Johns Wood', region: 'London', country: 'United Kingdom' },
  { name: 'Canary Wharf', region: 'London', country: 'United Kingdom' },
  { name: 'Clapham', region: 'London', country: 'United Kingdom' },
  { name: 'Islington', region: 'London', country: 'United Kingdom' },
  { name: 'Battersea', region: 'London', country: 'United Kingdom' },
  { name: 'Putney', region: 'London', country: 'United Kingdom' },
  { name: 'Barnes', region: 'London', country: 'United Kingdom' },
  { name: 'Dulwich', region: 'London', country: 'United Kingdom' },
  { name: 'Marylebone', region: 'London', country: 'United Kingdom' },
  // South East
  { name: 'Guildford', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Esher', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Cobham', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Weybridge', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Virginia Water', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Reigate', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Farnham', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Tunbridge Wells', region: 'Kent', country: 'United Kingdom' },
  { name: 'Sevenoaks', region: 'Kent', country: 'United Kingdom' },
  { name: 'Canterbury', region: 'Kent', country: 'United Kingdom' },
  { name: 'St Albans', region: 'Hertfordshire', country: 'United Kingdom' },
  { name: 'Beaconsfield', region: 'Buckinghamshire', country: 'United Kingdom' },
  { name: 'Gerrards Cross', region: 'Buckinghamshire', country: 'United Kingdom' },
  { name: 'Henley-on-Thames', region: 'Oxfordshire', country: 'United Kingdom' },
  { name: 'Marlow', region: 'Buckinghamshire', country: 'United Kingdom' },
  { name: 'Windsor', region: 'Berkshire', country: 'United Kingdom' },
  { name: 'Ascot', region: 'Berkshire', country: 'United Kingdom' },
  { name: 'Reading', region: 'Berkshire', country: 'United Kingdom' },
  { name: 'Maidenhead', region: 'Berkshire', country: 'United Kingdom' },
  { name: 'Winchester', region: 'Hampshire', country: 'United Kingdom' },
  // South West & West
  { name: 'Bath', region: 'Somerset', country: 'United Kingdom' },
  { name: 'Bristol', region: 'Bristol', country: 'United Kingdom' },
  { name: 'Cheltenham', region: 'Gloucestershire', country: 'United Kingdom' },
  { name: 'Cirencester', region: 'Gloucestershire', country: 'United Kingdom' },
  { name: 'Exeter', region: 'Devon', country: 'United Kingdom' },
  { name: 'Bournemouth', region: 'Dorset', country: 'United Kingdom' },
  { name: 'Poole', region: 'Dorset', country: 'United Kingdom' },
  { name: 'Salisbury', region: 'Wiltshire', country: 'United Kingdom' },
  // South Coast
  { name: 'Brighton', region: 'East Sussex', country: 'United Kingdom' },
  { name: 'Chichester', region: 'West Sussex', country: 'United Kingdom' },
  // East
  { name: 'Cambridge', region: 'Cambridgeshire', country: 'United Kingdom' },
  { name: 'Oxford', region: 'Oxfordshire', country: 'United Kingdom' },
  { name: 'Bury St Edmunds', region: 'Suffolk', country: 'United Kingdom' },
  { name: 'Norwich', region: 'Norfolk', country: 'United Kingdom' },
  // Midlands
  { name: 'Solihull', region: 'West Midlands', country: 'United Kingdom' },
  { name: 'Stratford-upon-Avon', region: 'Warwickshire', country: 'United Kingdom' },
  { name: 'Leamington Spa', region: 'Warwickshire', country: 'United Kingdom' },
  { name: 'Sutton Coldfield', region: 'West Midlands', country: 'United Kingdom' },
  { name: 'Nottingham', region: 'Nottinghamshire', country: 'United Kingdom' },
  { name: 'Leicester', region: 'Leicestershire', country: 'United Kingdom' },
  { name: 'Birmingham', region: 'West Midlands', country: 'United Kingdom' },
  // North West
  { name: 'Alderley Edge', region: 'Cheshire', country: 'United Kingdom' },
  { name: 'Wilmslow', region: 'Cheshire', country: 'United Kingdom' },
  { name: 'Knutsford', region: 'Cheshire', country: 'United Kingdom' },
  { name: 'Hale', region: 'Greater Manchester', country: 'United Kingdom' },
  { name: 'Didsbury', region: 'Greater Manchester', country: 'United Kingdom' },
  { name: 'Manchester', region: 'Greater Manchester', country: 'United Kingdom' },
  { name: 'Liverpool', region: 'Merseyside', country: 'United Kingdom' },
  { name: 'Chester', region: 'Cheshire', country: 'United Kingdom' },
  { name: 'Formby', region: 'Merseyside', country: 'United Kingdom' },
  // Yorkshire
  { name: 'Harrogate', region: 'North Yorkshire', country: 'United Kingdom' },
  { name: 'York', region: 'North Yorkshire', country: 'United Kingdom' },
  { name: 'Ilkley', region: 'West Yorkshire', country: 'United Kingdom' },
  { name: 'Leeds', region: 'West Yorkshire', country: 'United Kingdom' },
  { name: 'Sheffield', region: 'South Yorkshire', country: 'United Kingdom' },
  // North East
  { name: 'Newcastle upon Tyne', region: 'Tyne and Wear', country: 'United Kingdom' },
  { name: 'Durham', region: 'County Durham', country: 'United Kingdom' },
  { name: 'Jesmond', region: 'Tyne and Wear', country: 'United Kingdom' },
  // Scotland
  { name: 'Edinburgh', region: 'Scotland', country: 'United Kingdom' },
  { name: 'Glasgow', region: 'Scotland', country: 'United Kingdom' },
  { name: 'Aberdeen', region: 'Scotland', country: 'United Kingdom' },
  { name: 'St Andrews', region: 'Scotland', country: 'United Kingdom' },
  // Wales
  { name: 'Cardiff', region: 'Wales', country: 'United Kingdom' },
  { name: 'Swansea', region: 'Wales', country: 'United Kingdom' },
  // Northern Ireland
  { name: 'Belfast', region: 'Northern Ireland', country: 'United Kingdom' },
  // More South East
  { name: 'Twickenham', region: 'London', country: 'United Kingdom' },
  { name: 'Kingston upon Thames', region: 'London', country: 'United Kingdom' },
  { name: 'Epsom', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Woking', region: 'Surrey', country: 'United Kingdom' },
  { name: 'Horsham', region: 'West Sussex', country: 'United Kingdom' },
  { name: 'Newbury', region: 'Berkshire', country: 'United Kingdom' },
  { name: 'Harpenden', region: 'Hertfordshire', country: 'United Kingdom' },
  { name: 'Hitchin', region: 'Hertfordshire', country: 'United Kingdom' },
  { name: 'Hertford', region: 'Hertfordshire', country: 'United Kingdom' },
  { name: 'Loughton', region: 'Essex', country: 'United Kingdom' },
  { name: 'Brentwood', region: 'Essex', country: 'United Kingdom' },
  { name: 'Chigwell', region: 'Essex', country: 'United Kingdom' },
  { name: 'Leigh-on-Sea', region: 'Essex', country: 'United Kingdom' },
];

export const US_AFFLUENT_CITIES: CityData[] = [
  // California
  { name: 'Beverly Hills', region: 'California', country: 'United States' },
  { name: 'Santa Monica', region: 'California', country: 'United States' },
  { name: 'Malibu', region: 'California', country: 'United States' },
  { name: 'Newport Beach', region: 'California', country: 'United States' },
  { name: 'Laguna Beach', region: 'California', country: 'United States' },
  { name: 'Palo Alto', region: 'California', country: 'United States' },
  { name: 'Atherton', region: 'California', country: 'United States' },
  { name: 'Los Gatos', region: 'California', country: 'United States' },
  { name: 'Saratoga', region: 'California', country: 'United States' },
  { name: 'San Francisco', region: 'California', country: 'United States' },
  { name: 'La Jolla', region: 'California', country: 'United States' },
  { name: 'Coronado', region: 'California', country: 'United States' },
  { name: 'Pasadena', region: 'California', country: 'United States' },
  { name: 'Manhattan Beach', region: 'California', country: 'United States' },
  { name: 'Calabasas', region: 'California', country: 'United States' },
  { name: 'Danville', region: 'California', country: 'United States' },
  { name: 'Walnut Creek', region: 'California', country: 'United States' },
  { name: 'San Mateo', region: 'California', country: 'United States' },
  { name: 'Irvine', region: 'California', country: 'United States' },
  { name: 'Huntington Beach', region: 'California', country: 'United States' },
  // New York
  { name: 'Manhattan', region: 'New York', country: 'United States' },
  { name: 'Scarsdale', region: 'New York', country: 'United States' },
  { name: 'Rye', region: 'New York', country: 'United States' },
  { name: 'Great Neck', region: 'New York', country: 'United States' },
  { name: 'Garden City', region: 'New York', country: 'United States' },
  { name: 'Bronxville', region: 'New York', country: 'United States' },
  { name: 'Chappaqua', region: 'New York', country: 'United States' },
  { name: 'Bedford', region: 'New York', country: 'United States' },
  { name: 'Manhasset', region: 'New York', country: 'United States' },
  { name: 'Cold Spring Harbor', region: 'New York', country: 'United States' },
  // Florida
  { name: 'Miami Beach', region: 'Florida', country: 'United States' },
  { name: 'Boca Raton', region: 'Florida', country: 'United States' },
  { name: 'Palm Beach', region: 'Florida', country: 'United States' },
  { name: 'Naples', region: 'Florida', country: 'United States' },
  { name: 'Coral Gables', region: 'Florida', country: 'United States' },
  { name: 'Jupiter', region: 'Florida', country: 'United States' },
  { name: 'Sarasota', region: 'Florida', country: 'United States' },
  { name: 'Winter Park', region: 'Florida', country: 'United States' },
  { name: 'Key Biscayne', region: 'Florida', country: 'United States' },
  { name: 'Aventura', region: 'Florida', country: 'United States' },
  { name: 'Fort Lauderdale', region: 'Florida', country: 'United States' },
  { name: 'Delray Beach', region: 'Florida', country: 'United States' },
  { name: 'Tampa', region: 'Florida', country: 'United States' },
  { name: 'Windermere', region: 'Florida', country: 'United States' },
  { name: 'Ponte Vedra Beach', region: 'Florida', country: 'United States' },
  // Texas
  { name: 'Highland Park', region: 'Texas', country: 'United States' },
  { name: 'University Park', region: 'Texas', country: 'United States' },
  { name: 'Westlake', region: 'Texas', country: 'United States' },
  { name: 'The Woodlands', region: 'Texas', country: 'United States' },
  { name: 'Sugar Land', region: 'Texas', country: 'United States' },
  { name: 'Southlake', region: 'Texas', country: 'United States' },
  { name: 'Plano', region: 'Texas', country: 'United States' },
  { name: 'Frisco', region: 'Texas', country: 'United States' },
  { name: 'Austin', region: 'Texas', country: 'United States' },
  { name: 'Houston', region: 'Texas', country: 'United States' },
  // New Jersey / Connecticut
  { name: 'Short Hills', region: 'New Jersey', country: 'United States' },
  { name: 'Summit', region: 'New Jersey', country: 'United States' },
  { name: 'Princeton', region: 'New Jersey', country: 'United States' },
  { name: 'Ridgewood', region: 'New Jersey', country: 'United States' },
  { name: 'Hoboken', region: 'New Jersey', country: 'United States' },
  { name: 'Greenwich', region: 'Connecticut', country: 'United States' },
  { name: 'Westport', region: 'Connecticut', country: 'United States' },
  { name: 'Darien', region: 'Connecticut', country: 'United States' },
  { name: 'New Canaan', region: 'Connecticut', country: 'United States' },
  { name: 'Fairfield', region: 'Connecticut', country: 'United States' },
  // Massachusetts
  { name: 'Wellesley', region: 'Massachusetts', country: 'United States' },
  { name: 'Newton', region: 'Massachusetts', country: 'United States' },
  { name: 'Brookline', region: 'Massachusetts', country: 'United States' },
  { name: 'Lexington', region: 'Massachusetts', country: 'United States' },
  { name: 'Concord', region: 'Massachusetts', country: 'United States' },
  { name: 'Nantucket', region: 'Massachusetts', country: 'United States' },
  { name: 'Boston', region: 'Massachusetts', country: 'United States' },
  // Illinois / Midwest
  { name: 'Winnetka', region: 'Illinois', country: 'United States' },
  { name: 'Lake Forest', region: 'Illinois', country: 'United States' },
  { name: 'Hinsdale', region: 'Illinois', country: 'United States' },
  { name: 'Naperville', region: 'Illinois', country: 'United States' },
  { name: 'Highland Park', region: 'Illinois', country: 'United States' },
  { name: 'Chicago', region: 'Illinois', country: 'United States' },
  { name: 'Bloomfield Hills', region: 'Michigan', country: 'United States' },
  { name: 'Ann Arbor', region: 'Michigan', country: 'United States' },
  { name: 'Wayzata', region: 'Minnesota', country: 'United States' },
  { name: 'Edina', region: 'Minnesota', country: 'United States' },
  // Mid-Atlantic
  { name: 'Bethesda', region: 'Maryland', country: 'United States' },
  { name: 'Chevy Chase', region: 'Maryland', country: 'United States' },
  { name: 'Potomac', region: 'Maryland', country: 'United States' },
  { name: 'McLean', region: 'Virginia', country: 'United States' },
  { name: 'Great Falls', region: 'Virginia', country: 'United States' },
  { name: 'Arlington', region: 'Virginia', country: 'United States' },
  { name: 'Alexandria', region: 'Virginia', country: 'United States' },
  { name: 'Bryn Mawr', region: 'Pennsylvania', country: 'United States' },
  { name: 'Gladwyne', region: 'Pennsylvania', country: 'United States' },
  { name: 'Wayne', region: 'Pennsylvania', country: 'United States' },
  // Pacific Northwest
  { name: 'Mercer Island', region: 'Washington', country: 'United States' },
  { name: 'Bellevue', region: 'Washington', country: 'United States' },
  { name: 'Kirkland', region: 'Washington', country: 'United States' },
  { name: 'Seattle', region: 'Washington', country: 'United States' },
  { name: 'Lake Oswego', region: 'Oregon', country: 'United States' },
  { name: 'Portland', region: 'Oregon', country: 'United States' },
  // Colorado
  { name: 'Cherry Hills Village', region: 'Colorado', country: 'United States' },
  { name: 'Aspen', region: 'Colorado', country: 'United States' },
  { name: 'Boulder', region: 'Colorado', country: 'United States' },
  { name: 'Denver', region: 'Colorado', country: 'United States' },
  { name: 'Castle Rock', region: 'Colorado', country: 'United States' },
  // Arizona / Nevada
  { name: 'Scottsdale', region: 'Arizona', country: 'United States' },
  { name: 'Paradise Valley', region: 'Arizona', country: 'United States' },
  { name: 'Chandler', region: 'Arizona', country: 'United States' },
  { name: 'Las Vegas', region: 'Nevada', country: 'United States' },
  { name: 'Henderson', region: 'Nevada', country: 'United States' },
  // South
  { name: 'Buckhead', region: 'Georgia', country: 'United States' },
  { name: 'Alpharetta', region: 'Georgia', country: 'United States' },
  { name: 'Atlanta', region: 'Georgia', country: 'United States' },
  { name: 'Charleston', region: 'South Carolina', country: 'United States' },
  { name: 'Charlotte', region: 'North Carolina', country: 'United States' },
  { name: 'Raleigh', region: 'North Carolina', country: 'United States' },
  { name: 'Nashville', region: 'Tennessee', country: 'United States' },
  { name: 'Brentwood', region: 'Tennessee', country: 'United States' },
  // More major metros
  { name: 'Honolulu', region: 'Hawaii', country: 'United States' },
  { name: 'Salt Lake City', region: 'Utah', country: 'United States' },
  { name: 'Park City', region: 'Utah', country: 'United States' },
  { name: 'San Diego', region: 'California', country: 'United States' },
  { name: 'Santa Barbara', region: 'California', country: 'United States' },
  { name: 'Carmel-by-the-Sea', region: 'California', country: 'United States' },
  { name: 'Mill Valley', region: 'California', country: 'United States' },
  { name: 'Tiburon', region: 'California', country: 'United States' },
  { name: 'Rancho Santa Fe', region: 'California', country: 'United States' },
  { name: 'Palos Verdes Estates', region: 'California', country: 'United States' },
  { name: 'Westlake Village', region: 'California', country: 'United States' },
  { name: 'Thousand Oaks', region: 'California', country: 'United States' },
  { name: 'Encino', region: 'California', country: 'United States' },
  { name: 'Sherman Oaks', region: 'California', country: 'United States' },
  { name: 'Studio City', region: 'California', country: 'United States' },
  { name: 'West Hollywood', region: 'California', country: 'United States' },
  { name: 'Los Angeles', region: 'California', country: 'United States' },
  { name: 'San Jose', region: 'California', country: 'United States' },
  { name: 'Cupertino', region: 'California', country: 'United States' },
  { name: 'Mountain View', region: 'California', country: 'United States' },
  { name: 'Burlingame', region: 'California', country: 'United States' },
  { name: 'Hillsborough', region: 'California', country: 'United States' },
  { name: 'Ross', region: 'California', country: 'United States' },
  { name: 'Orinda', region: 'California', country: 'United States' },
  { name: 'Lafayette', region: 'California', country: 'United States' },
  { name: 'Pleasanton', region: 'California', country: 'United States' },
  // More NE / Mid-Atlantic
  { name: 'Stamford', region: 'Connecticut', country: 'United States' },
  { name: 'Weston', region: 'Connecticut', country: 'United States' },
  { name: 'Glastonbury', region: 'Connecticut', country: 'United States' },
  { name: 'Chatham', region: 'New Jersey', country: 'United States' },
  { name: 'Morristown', region: 'New Jersey', country: 'United States' },
  { name: 'Montclair', region: 'New Jersey', country: 'United States' },
  { name: 'Livingston', region: 'New Jersey', country: 'United States' },
  { name: 'Millburn', region: 'New Jersey', country: 'United States' },
  { name: 'East Hampton', region: 'New York', country: 'United States' },
  { name: 'Southampton', region: 'New York', country: 'United States' },
  { name: 'Montauk', region: 'New York', country: 'United States' },
  { name: 'Westbury', region: 'New York', country: 'United States' },
  { name: 'Oyster Bay', region: 'New York', country: 'United States' },
  { name: 'Saratoga Springs', region: 'New York', country: 'United States' },
  // More South / Southeast
  { name: 'Coral Springs', region: 'Florida', country: 'United States' },
  { name: 'Weston', region: 'Florida', country: 'United States' },
  { name: 'Parkland', region: 'Florida', country: 'United States' },
  { name: 'Wellington', region: 'Florida', country: 'United States' },
  { name: 'Celebration', region: 'Florida', country: 'United States' },
  { name: 'St Augustine', region: 'Florida', country: 'United States' },
  { name: 'Savannah', region: 'Georgia', country: 'United States' },
  { name: 'Birmingham', region: 'Alabama', country: 'United States' },
  { name: 'New Orleans', region: 'Louisiana', country: 'United States' },
  // More Texas
  { name: 'Katy', region: 'Texas', country: 'United States' },
  { name: 'Colleyville', region: 'Texas', country: 'United States' },
  { name: 'Flower Mound', region: 'Texas', country: 'United States' },
  { name: 'McKinney', region: 'Texas', country: 'United States' },
  { name: 'Allen', region: 'Texas', country: 'United States' },
  { name: 'San Antonio', region: 'Texas', country: 'United States' },
  { name: 'Dallas', region: 'Texas', country: 'United States' },
];

export const CA_AFFLUENT_CITIES: CityData[] = [
  // Ontario — Greater Toronto Area
  { name: 'Yorkville', region: 'Ontario', country: 'Canada' },
  { name: 'Forest Hill', region: 'Ontario', country: 'Canada' },
  { name: 'Rosedale', region: 'Ontario', country: 'Canada' },
  { name: 'The Bridle Path', region: 'Ontario', country: 'Canada' },
  { name: 'Lawrence Park', region: 'Ontario', country: 'Canada' },
  { name: 'King City', region: 'Ontario', country: 'Canada' },
  { name: 'Oakville', region: 'Ontario', country: 'Canada' },
  { name: 'Burlington', region: 'Ontario', country: 'Canada' },
  { name: 'Mississauga', region: 'Ontario', country: 'Canada' },
  { name: 'Richmond Hill', region: 'Ontario', country: 'Canada' },
  { name: 'Markham', region: 'Ontario', country: 'Canada' },
  { name: 'Vaughan', region: 'Ontario', country: 'Canada' },
  { name: 'Aurora', region: 'Ontario', country: 'Canada' },
  { name: 'Newmarket', region: 'Ontario', country: 'Canada' },
  { name: 'Whitby', region: 'Ontario', country: 'Canada' },
  { name: 'Toronto', region: 'Ontario', country: 'Canada' },
  { name: 'Etobicoke', region: 'Ontario', country: 'Canada' },
  { name: 'North York', region: 'Ontario', country: 'Canada' },
  { name: 'Scarborough', region: 'Ontario', country: 'Canada' },
  // Ontario — Other
  { name: 'Ottawa', region: 'Ontario', country: 'Canada' },
  { name: 'Rockcliffe Park', region: 'Ontario', country: 'Canada' },
  { name: 'Westboro', region: 'Ontario', country: 'Canada' },
  { name: 'Niagara-on-the-Lake', region: 'Ontario', country: 'Canada' },
  { name: 'Waterloo', region: 'Ontario', country: 'Canada' },
  { name: 'Kitchener', region: 'Ontario', country: 'Canada' },
  { name: 'London', region: 'Ontario', country: 'Canada' },
  { name: 'Hamilton', region: 'Ontario', country: 'Canada' },
  { name: 'Kingston', region: 'Ontario', country: 'Canada' },
  { name: 'Collingwood', region: 'Ontario', country: 'Canada' },
  { name: 'Muskoka', region: 'Ontario', country: 'Canada' },
  // British Columbia — Greater Vancouver
  { name: 'West Vancouver', region: 'British Columbia', country: 'Canada' },
  { name: 'North Vancouver', region: 'British Columbia', country: 'Canada' },
  { name: 'Shaughnessy', region: 'British Columbia', country: 'Canada' },
  { name: 'Kerrisdale', region: 'British Columbia', country: 'Canada' },
  { name: 'Point Grey', region: 'British Columbia', country: 'Canada' },
  { name: 'Kitsilano', region: 'British Columbia', country: 'Canada' },
  { name: 'Yaletown', region: 'British Columbia', country: 'Canada' },
  { name: 'Vancouver', region: 'British Columbia', country: 'Canada' },
  { name: 'Burnaby', region: 'British Columbia', country: 'Canada' },
  { name: 'Richmond', region: 'British Columbia', country: 'Canada' },
  { name: 'Surrey', region: 'British Columbia', country: 'Canada' },
  { name: 'White Rock', region: 'British Columbia', country: 'Canada' },
  { name: 'Langley', region: 'British Columbia', country: 'Canada' },
  { name: 'Coquitlam', region: 'British Columbia', country: 'Canada' },
  // British Columbia — Other
  { name: 'Victoria', region: 'British Columbia', country: 'Canada' },
  { name: 'Oak Bay', region: 'British Columbia', country: 'Canada' },
  { name: 'Kelowna', region: 'British Columbia', country: 'Canada' },
  { name: 'Whistler', region: 'British Columbia', country: 'Canada' },
  { name: 'Kamloops', region: 'British Columbia', country: 'Canada' },
  { name: 'Nanaimo', region: 'British Columbia', country: 'Canada' },
  // Alberta
  { name: 'Calgary', region: 'Alberta', country: 'Canada' },
  { name: 'Mount Royal', region: 'Alberta', country: 'Canada' },
  { name: 'Elbow Park', region: 'Alberta', country: 'Canada' },
  { name: 'Aspen Woods', region: 'Alberta', country: 'Canada' },
  { name: 'Springbank', region: 'Alberta', country: 'Canada' },
  { name: 'Canmore', region: 'Alberta', country: 'Canada' },
  { name: 'Edmonton', region: 'Alberta', country: 'Canada' },
  { name: 'Windermere', region: 'Alberta', country: 'Canada' },
  { name: 'St Albert', region: 'Alberta', country: 'Canada' },
  { name: 'Sherwood Park', region: 'Alberta', country: 'Canada' },
  // Quebec
  { name: 'Westmount', region: 'Quebec', country: 'Canada' },
  { name: 'Outremont', region: 'Quebec', country: 'Canada' },
  { name: 'Mont-Royal', region: 'Quebec', country: 'Canada' },
  { name: 'Montreal', region: 'Quebec', country: 'Canada' },
  { name: 'Laval', region: 'Quebec', country: 'Canada' },
  { name: 'Brossard', region: 'Quebec', country: 'Canada' },
  { name: 'Longueuil', region: 'Quebec', country: 'Canada' },
  { name: 'Quebec City', region: 'Quebec', country: 'Canada' },
  { name: 'Sillery', region: 'Quebec', country: 'Canada' },
  { name: 'Tremblant', region: 'Quebec', country: 'Canada' },
  // Manitoba
  { name: 'Winnipeg', region: 'Manitoba', country: 'Canada' },
  { name: 'Tuxedo', region: 'Manitoba', country: 'Canada' },
  // Saskatchewan
  { name: 'Saskatoon', region: 'Saskatchewan', country: 'Canada' },
  { name: 'Regina', region: 'Saskatchewan', country: 'Canada' },
  // Atlantic
  { name: 'Halifax', region: 'Nova Scotia', country: 'Canada' },
  { name: 'Fredericton', region: 'New Brunswick', country: 'Canada' },
  { name: 'St Johns', region: 'Newfoundland', country: 'Canada' },
  { name: 'Charlottetown', region: 'Prince Edward Island', country: 'Canada' },
];

// Group by region for UI display
export function getCitiesByRegion(cities: CityData[]): Record<string, CityData[]> {
  const grouped: Record<string, CityData[]> = {};
  for (const city of cities) {
    if (!grouped[city.region]) grouped[city.region] = [];
    grouped[city.region].push(city);
  }
  return grouped;
}

// Get all unique regions
export function getRegions(cities: CityData[]): string[] {
  return [...new Set(cities.map(c => c.region))].sort();
}
