-- Affluent Areas Seed Data (215 areas: 75 UK, 100 US, 40 CA)
-- Run AFTER add-affluent-areas.sql

-- ═══════════════════════════════════════════════════════════
-- UK — LONDON TIER 1 (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Mayfair', 'London', 'UK', 'London', 1, 'aesthetic clinic Mayfair', 'aesthetics Mayfair', 'skin clinic Mayfair', 51.507400, -0.147800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Knightsbridge', 'London', 'UK', 'London', 1, 'aesthetic clinic Knightsbridge', 'aesthetics Knightsbridge', 'skin clinic Knightsbridge', 51.501500, -0.160700, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Chelsea', 'London', 'UK', 'London', 1, 'aesthetic clinic Chelsea', 'aesthetics Chelsea', 'skin clinic Chelsea', 51.487500, -0.168700, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Belgravia', 'London', 'UK', 'London', 1, 'aesthetic clinic Belgravia', 'aesthetics Belgravia', 'skin clinic Belgravia', 51.497500, -0.153000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Kensington', 'London', 'UK', 'London', 1, 'aesthetic clinic Kensington', 'aesthetics Kensington', 'skin clinic Kensington', 51.499000, -0.188900, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('South Kensington', 'London', 'UK', 'London', 1, 'aesthetic clinic South Kensington', 'aesthetics South Kensington', 'skin clinic South Kensington', 51.494200, -0.174500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Holland Park', 'London', 'UK', 'London', 1, 'aesthetic clinic Holland Park', 'aesthetics Holland Park', 'skin clinic Holland Park', 51.502800, -0.206500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Notting Hill', 'London', 'UK', 'London', 1, 'aesthetic clinic Notting Hill', 'aesthetics Notting Hill', 'skin clinic Notting Hill', 51.509300, -0.196300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('St Johns Wood', 'London', 'UK', 'London', 1, 'aesthetic clinic St Johns Wood', 'aesthetics St Johns Wood', 'skin clinic St Johns Wood', 51.532300, -0.174900, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Primrose Hill', 'London', 'UK', 'London', 1, 'aesthetic clinic Primrose Hill', 'aesthetics Primrose Hill', 'skin clinic Primrose Hill', 51.539200, -0.160500, 1);

-- ═══════════════════════════════════════════════════════════
-- UK — LONDON TIER 2 (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Hampstead', 'London', 'UK', 'London', 2, 'aesthetic clinic Hampstead', 'aesthetics Hampstead', 'skin clinic Hampstead', 51.556500, -0.178100, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Richmond', 'London', 'UK', 'London', 2, 'aesthetic clinic Richmond', 'aesthetics Richmond', 'skin clinic Richmond', 51.461300, -0.303700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Wimbledon Village', 'London', 'UK', 'London', 2, 'aesthetic clinic Wimbledon Village', 'aesthetics Wimbledon Village', 'skin clinic Wimbledon Village', 51.434000, -0.213300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Chiswick', 'London', 'UK', 'London', 2, 'aesthetic clinic Chiswick', 'aesthetics Chiswick', 'skin clinic Chiswick', 51.492700, -0.267400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Fulham', 'London', 'UK', 'London', 2, 'aesthetic clinic Fulham', 'aesthetics Fulham', 'skin clinic Fulham', 51.473300, -0.194900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Barnes', 'London', 'UK', 'London', 2, 'aesthetic clinic Barnes', 'aesthetics Barnes', 'skin clinic Barnes', 51.467700, -0.240600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Dulwich Village', 'London', 'UK', 'London', 2, 'aesthetic clinic Dulwich Village', 'aesthetics Dulwich Village', 'skin clinic Dulwich Village', 51.445200, -0.085900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Battersea', 'London', 'UK', 'London', 2, 'aesthetic clinic Battersea', 'aesthetics Battersea', 'skin clinic Battersea', 51.475300, -0.154700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Islington', 'London', 'UK', 'London', 2, 'aesthetic clinic Islington', 'aesthetics Islington', 'skin clinic Islington', 51.536200, -0.103300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Marylebone', 'London', 'UK', 'London', 2, 'aesthetic clinic Marylebone', 'aesthetics Marylebone', 'skin clinic Marylebone', 51.522500, -0.153700, 2);

-- ═══════════════════════════════════════════════════════════
-- UK — LONDON TIER 3 (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Canary Wharf', 'London', 'UK', 'London', 3, 'aesthetic clinic Canary Wharf', 'aesthetics Canary Wharf', 'skin clinic Canary Wharf', 51.505400, -0.023500, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Greenwich', 'London', 'UK', 'London', 3, 'aesthetic clinic Greenwich', 'aesthetics Greenwich', 'skin clinic Greenwich', 51.476900, -0.000500, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Putney', 'London', 'UK', 'London', 3, 'aesthetic clinic Putney', 'aesthetics Putney', 'skin clinic Putney', 51.461400, -0.216900, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Clapham', 'London', 'UK', 'London', 3, 'aesthetic clinic Clapham', 'aesthetics Clapham', 'skin clinic Clapham', 51.462000, -0.138000, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Highgate', 'London', 'UK', 'London', 3, 'aesthetic clinic Highgate', 'aesthetics Highgate', 'skin clinic Highgate', 51.571700, -0.146700, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Muswell Hill', 'London', 'UK', 'London', 3, 'aesthetic clinic Muswell Hill', 'aesthetics Muswell Hill', 'skin clinic Muswell Hill', 51.589300, -0.144100, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Blackheath', 'London', 'UK', 'London', 3, 'aesthetic clinic Blackheath', 'aesthetics Blackheath', 'skin clinic Blackheath', 51.465600, -0.009800, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Twickenham', 'London', 'UK', 'London', 3, 'aesthetic clinic Twickenham', 'aesthetics Twickenham', 'skin clinic Twickenham', 51.449000, -0.337200, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Kingston upon Thames', 'London', 'UK', 'London', 3, 'aesthetic clinic Kingston upon Thames', 'aesthetics Kingston upon Thames', 'skin clinic Kingston upon Thames', 51.410300, -0.306400, 3);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Ealing', 'London', 'UK', 'London', 3, 'aesthetic clinic Ealing', 'aesthetics Ealing', 'skin clinic Ealing', 51.513000, -0.308900, 3);

-- ═══════════════════════════════════════════════════════════
-- UK — SOUTH EAST (15)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Virginia Water', 'Virginia Water', 'UK', 'South East', 1, 'aesthetic clinic Virginia Water', 'aesthetics Virginia Water', 'skin clinic Virginia Water', 51.402300, -0.564700, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Cobham', 'Cobham', 'UK', 'South East', 1, 'aesthetic clinic Cobham', 'aesthetics Cobham', 'skin clinic Cobham', 51.327900, -0.412000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Esher', 'Esher', 'UK', 'South East', 1, 'aesthetic clinic Esher', 'aesthetics Esher', 'skin clinic Esher', 51.369100, -0.365200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Guildford', 'Guildford', 'UK', 'South East', 2, 'aesthetic clinic Guildford', 'aesthetics Guildford', 'skin clinic Guildford', 51.236200, -0.570400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Gerrards Cross', 'Gerrards Cross', 'UK', 'South East', 1, 'aesthetic clinic Gerrards Cross', 'aesthetics Gerrards Cross', 'skin clinic Gerrards Cross', 51.587900, -0.556200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Beaconsfield', 'Beaconsfield', 'UK', 'South East', 1, 'aesthetic clinic Beaconsfield', 'aesthetics Beaconsfield', 'skin clinic Beaconsfield', 51.602100, -0.637400, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Henley-on-Thames', 'Henley-on-Thames', 'UK', 'South East', 1, 'aesthetic clinic Henley-on-Thames', 'aesthetics Henley-on-Thames', 'skin clinic Henley-on-Thames', 51.535500, -0.899700, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Tunbridge Wells', 'Tunbridge Wells', 'UK', 'South East', 2, 'aesthetic clinic Tunbridge Wells', 'aesthetics Tunbridge Wells', 'skin clinic Tunbridge Wells', 51.132500, -0.263700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Sevenoaks', 'Sevenoaks', 'UK', 'South East', 2, 'aesthetic clinic Sevenoaks', 'aesthetics Sevenoaks', 'skin clinic Sevenoaks', 51.272000, 0.190900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('St Albans', 'St Albans', 'UK', 'South East', 2, 'aesthetic clinic St Albans', 'aesthetics St Albans', 'skin clinic St Albans', 51.755200, -0.336100, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Harpenden', 'Harpenden', 'UK', 'South East', 2, 'aesthetic clinic Harpenden', 'aesthetics Harpenden', 'skin clinic Harpenden', 51.814600, -0.356600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Reigate', 'Reigate', 'UK', 'South East', 2, 'aesthetic clinic Reigate', 'aesthetics Reigate', 'skin clinic Reigate', 51.237300, -0.205000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Farnham', 'Farnham', 'UK', 'South East', 2, 'aesthetic clinic Farnham', 'aesthetics Farnham', 'skin clinic Farnham', 51.214600, -0.799000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Marlow', 'Marlow', 'UK', 'South East', 2, 'aesthetic clinic Marlow', 'aesthetics Marlow', 'skin clinic Marlow', 51.571400, -0.774300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Windsor', 'Windsor', 'UK', 'South East', 2, 'aesthetic clinic Windsor', 'aesthetics Windsor', 'skin clinic Windsor', 51.481600, -0.610800, 2);

-- ═══════════════════════════════════════════════════════════
-- UK — SOUTH / SOUTHWEST (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Bath', 'Bath', 'UK', 'South West', 1, 'aesthetic clinic Bath', 'aesthetics Bath', 'skin clinic Bath', 51.381100, -2.359000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Sandbanks Poole', 'Poole', 'UK', 'South West', 1, 'aesthetic clinic Sandbanks', 'aesthetics Poole', 'skin clinic Poole', 50.717500, -1.978000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Bournemouth Westbourne', 'Bournemouth', 'UK', 'South West', 2, 'aesthetic clinic Bournemouth', 'aesthetics Westbourne', 'skin clinic Bournemouth', 50.719200, -1.880800, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Cheltenham', 'Cheltenham', 'UK', 'South West', 2, 'aesthetic clinic Cheltenham', 'aesthetics Cheltenham', 'skin clinic Cheltenham', 51.899400, -2.078300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Clifton Bristol', 'Bristol', 'UK', 'South West', 2, 'aesthetic clinic Clifton', 'aesthetics Bristol', 'skin clinic Clifton Bristol', 51.455500, -2.620800, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Topsham Exeter', 'Exeter', 'UK', 'South West', 2, 'aesthetic clinic Topsham', 'aesthetics Exeter', 'skin clinic Exeter', 50.718400, -3.533900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Chichester', 'Chichester', 'UK', 'South West', 2, 'aesthetic clinic Chichester', 'aesthetics Chichester', 'skin clinic Chichester', 50.836500, -0.779200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Hove Brighton', 'Brighton', 'UK', 'South West', 2, 'aesthetic clinic Hove', 'aesthetics Brighton', 'skin clinic Brighton', 50.822500, -0.137200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Romsey Southampton', 'Southampton', 'UK', 'South West', 2, 'aesthetic clinic Romsey', 'aesthetics Southampton', 'skin clinic Romsey', 50.909700, -1.404400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Winchester', 'Winchester', 'UK', 'South West', 2, 'aesthetic clinic Winchester', 'aesthetics Winchester', 'skin clinic Winchester', 51.063200, -1.308000, 2);

-- ═══════════════════════════════════════════════════════════
-- UK — NORTH (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Alderley Edge', 'Alderley Edge', 'UK', 'North', 1, 'aesthetic clinic Alderley Edge', 'aesthetics Alderley Edge', 'skin clinic Alderley Edge', 53.303900, -2.236800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Wilmslow', 'Wilmslow', 'UK', 'North', 1, 'aesthetic clinic Wilmslow', 'aesthetics Wilmslow', 'skin clinic Wilmslow', 53.327000, -2.226500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Hale Bowdon', 'Altrincham', 'UK', 'North', 1, 'aesthetic clinic Hale', 'aesthetics Bowdon', 'skin clinic Hale Bowdon', 53.378000, -2.348000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Harrogate', 'Harrogate', 'UK', 'North', 2, 'aesthetic clinic Harrogate', 'aesthetics Harrogate', 'skin clinic Harrogate', 53.992100, -1.541800, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Ilkley', 'Ilkley', 'UK', 'North', 2, 'aesthetic clinic Ilkley', 'aesthetics Ilkley', 'skin clinic Ilkley', 53.924800, -1.822500, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Roundhay Leeds', 'Leeds', 'UK', 'North', 2, 'aesthetic clinic Roundhay', 'aesthetics Leeds', 'skin clinic Roundhay Leeds', 53.832100, -1.532900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('York', 'York', 'UK', 'North', 2, 'aesthetic clinic York', 'aesthetics York', 'skin clinic York', 53.959100, -1.081500, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Jesmond Newcastle', 'Newcastle', 'UK', 'North', 2, 'aesthetic clinic Jesmond', 'aesthetics Newcastle', 'skin clinic Jesmond', 54.978300, -1.617800, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Stokesley', 'Stokesley', 'UK', 'North', 2, 'aesthetic clinic Stokesley', 'aesthetics Stokesley', 'skin clinic Stokesley', 54.471300, -1.350400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Chester', 'Chester', 'UK', 'North', 2, 'aesthetic clinic Chester', 'aesthetics Chester', 'skin clinic Chester', 53.193000, -2.893100, 2);

-- ═══════════════════════════════════════════════════════════
-- UK — MIDLANDS (5)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Solihull', 'Solihull', 'UK', 'Midlands', 2, 'aesthetic clinic Solihull', 'aesthetics Solihull', 'skin clinic Solihull', 52.411400, -1.774300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Edgbaston Birmingham', 'Birmingham', 'UK', 'Midlands', 2, 'aesthetic clinic Edgbaston', 'aesthetics Birmingham', 'skin clinic Edgbaston', 52.471400, -1.922700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Stratford-upon-Avon', 'Stratford-upon-Avon', 'UK', 'Midlands', 2, 'aesthetic clinic Stratford-upon-Avon', 'aesthetics Stratford-upon-Avon', 'skin clinic Stratford-upon-Avon', 52.191700, -1.708300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('West Bridgford Nottingham', 'Nottingham', 'UK', 'Midlands', 2, 'aesthetic clinic West Bridgford', 'aesthetics Nottingham', 'skin clinic West Bridgford', 52.930600, -1.126000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Stoneygate Leicester', 'Leicester', 'UK', 'Midlands', 2, 'aesthetic clinic Stoneygate', 'aesthetics Leicester', 'skin clinic Stoneygate', 52.623500, -1.098800, 2);

-- ═══════════════════════════════════════════════════════════
-- UK — SCOTLAND (5)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Edinburgh New Town', 'Edinburgh', 'UK', 'Scotland', 1, 'aesthetic clinic Edinburgh New Town', 'aesthetics Edinburgh', 'skin clinic Edinburgh', 55.953300, -3.188300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Morningside Edinburgh', 'Edinburgh', 'UK', 'Scotland', 2, 'aesthetic clinic Morningside', 'aesthetics Morningside Edinburgh', 'skin clinic Morningside', 55.924800, -3.208700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Glasgow West End', 'Glasgow', 'UK', 'Scotland', 2, 'aesthetic clinic Glasgow West End', 'aesthetics Glasgow', 'skin clinic Glasgow West End', 55.870600, -4.297600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Aberdeen West End', 'Aberdeen', 'UK', 'Scotland', 2, 'aesthetic clinic Aberdeen', 'aesthetics Aberdeen', 'skin clinic Aberdeen', 57.149700, -2.094300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('St Andrews', 'St Andrews', 'UK', 'Scotland', 2, 'aesthetic clinic St Andrews', 'aesthetics St Andrews', 'skin clinic St Andrews', 56.339800, -2.796700, 2);

-- ═══════════════════════════════════════════════════════════
-- US — CALIFORNIA (14)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Beverly Hills', 'Los Angeles', 'US', 'California', 1, 'medspa Beverly Hills', 'medical spa Beverly Hills', 'aesthetic clinic Beverly Hills', 34.073600, -118.400400, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Bel Air', 'Los Angeles', 'US', 'California', 1, 'medspa Bel Air', 'medical spa Bel Air', 'aesthetic clinic Bel Air', 34.082600, -118.461200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Santa Monica', 'Los Angeles', 'US', 'California', 1, 'medspa Santa Monica', 'medical spa Santa Monica', 'aesthetic clinic Santa Monica', 34.019500, -118.491200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Newport Beach', 'Newport Beach', 'US', 'California', 1, 'medspa Newport Beach', 'medical spa Newport Beach', 'aesthetic clinic Newport Beach', 33.618900, -117.928900, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Laguna Beach', 'Laguna Beach', 'US', 'California', 1, 'medspa Laguna Beach', 'medical spa Laguna Beach', 'aesthetic clinic Laguna Beach', 33.542700, -117.785400, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('La Jolla', 'San Diego', 'US', 'California', 1, 'medspa La Jolla', 'medical spa La Jolla', 'aesthetic clinic La Jolla', 32.832800, -117.271300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Palo Alto', 'Palo Alto', 'US', 'California', 1, 'medspa Palo Alto', 'medical spa Palo Alto', 'aesthetic clinic Palo Alto', 37.441900, -122.143000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Malibu', 'Los Angeles', 'US', 'California', 1, 'medspa Malibu', 'medical spa Malibu', 'aesthetic clinic Malibu', 34.025900, -118.779800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Calabasas', 'Los Angeles', 'US', 'California', 2, 'medspa Calabasas', 'medical spa Calabasas', 'aesthetic clinic Calabasas', 34.136700, -118.660900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Manhattan Beach', 'Los Angeles', 'US', 'California', 2, 'medspa Manhattan Beach', 'medical spa Manhattan Beach', 'aesthetic clinic Manhattan Beach', 33.884700, -118.410900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Pasadena', 'Pasadena', 'US', 'California', 2, 'medspa Pasadena', 'medical spa Pasadena', 'aesthetic clinic Pasadena', 34.147800, -118.144500, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Walnut Creek', 'Walnut Creek', 'US', 'California', 2, 'medspa Walnut Creek', 'medical spa Walnut Creek', 'aesthetic clinic Walnut Creek', 37.910100, -122.065200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Carmel', 'Carmel', 'US', 'California', 2, 'medspa Carmel', 'medical spa Carmel', 'aesthetic clinic Carmel', 36.555200, -121.923300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Sausalito', 'Sausalito', 'US', 'California', 2, 'medspa Sausalito', 'medical spa Sausalito', 'aesthetic clinic Sausalito', 37.859100, -122.485200, 2);

-- ═══════════════════════════════════════════════════════════
-- US — FLORIDA (12)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Miami Beach', 'Miami', 'US', 'Florida', 1, 'medspa Miami Beach', 'medical spa Miami Beach', 'aesthetic clinic Miami Beach', 25.790700, -80.130000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Coral Gables', 'Miami', 'US', 'Florida', 1, 'medspa Coral Gables', 'medical spa Coral Gables', 'aesthetic clinic Coral Gables', 25.721700, -80.268400, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Boca Raton', 'Boca Raton', 'US', 'Florida', 1, 'medspa Boca Raton', 'medical spa Boca Raton', 'aesthetic clinic Boca Raton', 26.368300, -80.128900, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Palm Beach', 'Palm Beach', 'US', 'Florida', 1, 'medspa Palm Beach', 'medical spa Palm Beach', 'aesthetic clinic Palm Beach', 26.705600, -80.036400, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Naples', 'Naples', 'US', 'Florida', 1, 'medspa Naples', 'medical spa Naples', 'aesthetic clinic Naples', 26.142000, -81.794800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Sarasota', 'Sarasota', 'US', 'Florida', 2, 'medspa Sarasota', 'medical spa Sarasota', 'aesthetic clinic Sarasota', 27.336400, -82.530700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Winter Park', 'Orlando', 'US', 'Florida', 2, 'medspa Winter Park', 'medical spa Winter Park', 'aesthetic clinic Winter Park', 28.599900, -81.339200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Hyde Park Tampa', 'Tampa', 'US', 'Florida', 2, 'medspa Hyde Park Tampa', 'medical spa Tampa', 'aesthetic clinic Hyde Park Tampa', 27.934100, -82.465400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Las Olas Fort Lauderdale', 'Fort Lauderdale', 'US', 'Florida', 2, 'medspa Las Olas', 'medical spa Fort Lauderdale', 'aesthetic clinic Fort Lauderdale', 26.115300, -80.136500, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Jupiter', 'Jupiter', 'US', 'Florida', 2, 'medspa Jupiter', 'medical spa Jupiter', 'aesthetic clinic Jupiter', 26.934200, -80.094200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Ponte Vedra Beach', 'Jacksonville', 'US', 'Florida', 2, 'medspa Ponte Vedra Beach', 'medical spa Ponte Vedra', 'aesthetic clinic Ponte Vedra', 30.239700, -81.385600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Key Biscayne', 'Miami', 'US', 'Florida', 2, 'medspa Key Biscayne', 'medical spa Key Biscayne', 'aesthetic clinic Key Biscayne', 25.691400, -80.162800, 2);

-- ═══════════════════════════════════════════════════════════
-- US — ARIZONA (5)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Scottsdale', 'Scottsdale', 'US', 'Arizona', 1, 'medspa Scottsdale', 'medical spa Scottsdale', 'aesthetic clinic Scottsdale', 33.494200, -111.926100, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Paradise Valley', 'Phoenix', 'US', 'Arizona', 1, 'medspa Paradise Valley', 'medical spa Paradise Valley', 'aesthetic clinic Paradise Valley', 33.531000, -111.942600, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Cave Creek', 'Phoenix', 'US', 'Arizona', 2, 'medspa Cave Creek', 'medical spa Cave Creek', 'aesthetic clinic Cave Creek', 33.831400, -111.950700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Arcadia Phoenix', 'Phoenix', 'US', 'Arizona', 2, 'medspa Arcadia Phoenix', 'medical spa Arcadia', 'aesthetic clinic Arcadia Phoenix', 33.485400, -111.979400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Sedona', 'Sedona', 'US', 'Arizona', 2, 'medspa Sedona', 'medical spa Sedona', 'aesthetic clinic Sedona', 34.869700, -111.761000, 2);

-- ═══════════════════════════════════════════════════════════
-- US — TEXAS (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Highland Park Dallas', 'Dallas', 'US', 'Texas', 1, 'medspa Highland Park Dallas', 'medical spa Highland Park', 'aesthetic clinic Highland Park Dallas', 32.833500, -96.790800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('University Park Dallas', 'Dallas', 'US', 'Texas', 1, 'medspa University Park Dallas', 'medical spa University Park', 'aesthetic clinic University Park Dallas', 32.849800, -96.800000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Southlake', 'Dallas', 'US', 'Texas', 1, 'medspa Southlake', 'medical spa Southlake', 'aesthetic clinic Southlake', 32.941300, -97.134200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Westlake Austin', 'Austin', 'US', 'Texas', 1, 'medspa Westlake Austin', 'medical spa Westlake', 'aesthetic clinic Westlake Austin', 30.453900, -97.800200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('River Oaks Houston', 'Houston', 'US', 'Texas', 1, 'medspa River Oaks Houston', 'medical spa River Oaks', 'aesthetic clinic River Oaks Houston', 29.749400, -95.423300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('The Woodlands', 'Houston', 'US', 'Texas', 2, 'medspa The Woodlands', 'medical spa The Woodlands', 'aesthetic clinic The Woodlands', 30.165800, -95.461300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('West University Place Houston', 'Houston', 'US', 'Texas', 2, 'medspa West University Place', 'medical spa West University', 'aesthetic clinic West University Houston', 29.717400, -95.432100, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Alamo Heights San Antonio', 'San Antonio', 'US', 'Texas', 2, 'medspa Alamo Heights', 'medical spa Alamo Heights', 'aesthetic clinic Alamo Heights', 29.484000, -98.465000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Frisco', 'Dallas', 'US', 'Texas', 2, 'medspa Frisco', 'medical spa Frisco', 'aesthetic clinic Frisco', 33.150700, -96.823600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Plano West', 'Dallas', 'US', 'Texas', 2, 'medspa Plano', 'medical spa Plano', 'aesthetic clinic Plano', 33.019800, -96.751900, 2);

-- ═══════════════════════════════════════════════════════════
-- US — NEW YORK / NORTHEAST (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Upper East Side', 'New York', 'US', 'New York', 1, 'medspa Upper East Side', 'medical spa Upper East Side', 'aesthetic clinic Upper East Side', 40.773600, -73.956600, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Tribeca', 'New York', 'US', 'New York', 1, 'medspa Tribeca', 'medical spa Tribeca', 'aesthetic clinic Tribeca', 40.716300, -74.008600, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('SoHo', 'New York', 'US', 'New York', 1, 'medspa SoHo', 'medical spa SoHo', 'aesthetic clinic SoHo NYC', 40.723300, -73.998500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Greenwich CT', 'Greenwich', 'US', 'New York', 1, 'medspa Greenwich CT', 'medical spa Greenwich', 'aesthetic clinic Greenwich CT', 41.026200, -73.628200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Westport CT', 'Westport', 'US', 'New York', 1, 'medspa Westport CT', 'medical spa Westport', 'aesthetic clinic Westport CT', 41.141500, -73.357900, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Scarsdale', 'New York', 'US', 'New York', 1, 'medspa Scarsdale', 'medical spa Scarsdale', 'aesthetic clinic Scarsdale', 40.978800, -73.784600, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Great Neck', 'New York', 'US', 'New York', 2, 'medspa Great Neck', 'medical spa Great Neck', 'aesthetic clinic Great Neck', 40.800700, -73.728200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Garden City', 'New York', 'US', 'New York', 2, 'medspa Garden City', 'medical spa Garden City', 'aesthetic clinic Garden City NY', 40.726800, -73.634300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Hamptons', 'New York', 'US', 'New York', 1, 'medspa Hamptons', 'medical spa Hamptons', 'aesthetic clinic Hamptons', 40.963200, -72.184900, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Rye', 'New York', 'US', 'New York', 2, 'medspa Rye NY', 'medical spa Rye', 'aesthetic clinic Rye NY', 40.980700, -73.683500, 2);

-- ═══════════════════════════════════════════════════════════
-- US — NORTHEAST METRO (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Back Bay Boston', 'Boston', 'US', 'Northeast', 1, 'medspa Back Bay Boston', 'medical spa Back Bay', 'aesthetic clinic Back Bay Boston', 42.350300, -71.081000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Wellesley', 'Boston', 'US', 'Northeast', 1, 'medspa Wellesley', 'medical spa Wellesley', 'aesthetic clinic Wellesley', 42.296800, -71.292400, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Newton', 'Boston', 'US', 'Northeast', 2, 'medspa Newton MA', 'medical spa Newton', 'aesthetic clinic Newton MA', 42.337000, -71.209200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Princeton NJ', 'Princeton', 'US', 'Northeast', 1, 'medspa Princeton', 'medical spa Princeton NJ', 'aesthetic clinic Princeton', 40.357300, -74.667200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Summit NJ', 'Summit', 'US', 'Northeast', 2, 'medspa Summit NJ', 'medical spa Summit', 'aesthetic clinic Summit NJ', 40.715700, -74.364300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Short Hills NJ', 'Short Hills', 'US', 'Northeast', 1, 'medspa Short Hills', 'medical spa Short Hills', 'aesthetic clinic Short Hills NJ', 40.739800, -74.324900, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Bethesda MD', 'Washington DC', 'US', 'Northeast', 1, 'medspa Bethesda', 'medical spa Bethesda MD', 'aesthetic clinic Bethesda', 38.984700, -77.094700, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('McLean VA', 'Washington DC', 'US', 'Northeast', 1, 'medspa McLean VA', 'medical spa McLean', 'aesthetic clinic McLean Virginia', 38.933900, -77.177300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Chevy Chase MD', 'Washington DC', 'US', 'Northeast', 1, 'medspa Chevy Chase', 'medical spa Chevy Chase MD', 'aesthetic clinic Chevy Chase', 38.998100, -77.084200, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Old Town Alexandria VA', 'Washington DC', 'US', 'Northeast', 2, 'medspa Old Town Alexandria', 'medical spa Alexandria VA', 'aesthetic clinic Alexandria VA', 38.804900, -77.047000, 2);

-- ═══════════════════════════════════════════════════════════
-- US — SOUTHEAST (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Buckhead Atlanta', 'Atlanta', 'US', 'Southeast', 1, 'medspa Buckhead', 'medical spa Buckhead Atlanta', 'aesthetic clinic Buckhead', 33.838100, -84.379300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Alpharetta', 'Atlanta', 'US', 'Southeast', 2, 'medspa Alpharetta', 'medical spa Alpharetta', 'aesthetic clinic Alpharetta', 34.075400, -84.294100, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Myers Park Charlotte', 'Charlotte', 'US', 'Southeast', 2, 'medspa Myers Park Charlotte', 'medical spa Charlotte', 'aesthetic clinic Myers Park', 35.188000, -80.833600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('North Hills Raleigh', 'Raleigh', 'US', 'Southeast', 2, 'medspa North Hills Raleigh', 'medical spa Raleigh', 'aesthetic clinic North Hills Raleigh', 35.838000, -78.640300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Belle Meade Nashville', 'Nashville', 'US', 'Southeast', 1, 'medspa Belle Meade Nashville', 'medical spa Nashville', 'aesthetic clinic Belle Meade', 36.103400, -86.859800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Franklin TN', 'Nashville', 'US', 'Southeast', 2, 'medspa Franklin TN', 'medical spa Franklin Tennessee', 'aesthetic clinic Franklin TN', 35.925100, -86.868900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Mount Pleasant Charleston', 'Charleston', 'US', 'Southeast', 2, 'medspa Mount Pleasant', 'medical spa Charleston SC', 'aesthetic clinic Mount Pleasant', 32.832300, -79.828400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Hilton Head', 'Hilton Head', 'US', 'Southeast', 2, 'medspa Hilton Head', 'medical spa Hilton Head', 'aesthetic clinic Hilton Head', 32.216300, -80.752600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Historic Savannah', 'Savannah', 'US', 'Southeast', 2, 'medspa Savannah', 'medical spa Savannah GA', 'aesthetic clinic Savannah', 32.080900, -81.091200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Mountain Brook Birmingham AL', 'Birmingham', 'US', 'Southeast', 2, 'medspa Mountain Brook', 'medical spa Birmingham AL', 'aesthetic clinic Mountain Brook', 33.480900, -86.745600, 2);

-- ═══════════════════════════════════════════════════════════
-- US — MIDWEST (8)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Lincoln Park Chicago', 'Chicago', 'US', 'Midwest', 1, 'medspa Lincoln Park Chicago', 'medical spa Lincoln Park', 'aesthetic clinic Lincoln Park Chicago', 41.921400, -87.651300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Naperville', 'Chicago', 'US', 'Midwest', 2, 'medspa Naperville', 'medical spa Naperville', 'aesthetic clinic Naperville', 41.750800, -88.153500, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Hinsdale', 'Chicago', 'US', 'Midwest', 1, 'medspa Hinsdale', 'medical spa Hinsdale', 'aesthetic clinic Hinsdale', 41.800800, -87.937000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Birmingham MI', 'Detroit', 'US', 'Midwest', 1, 'medspa Birmingham MI', 'medical spa Birmingham Michigan', 'aesthetic clinic Birmingham MI', 42.546700, -83.211300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Bloomfield Hills MI', 'Detroit', 'US', 'Midwest', 1, 'medspa Bloomfield Hills', 'medical spa Bloomfield Hills', 'aesthetic clinic Bloomfield Hills', 42.583600, -83.245500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Upper Arlington OH', 'Columbus', 'US', 'Midwest', 2, 'medspa Upper Arlington', 'medical spa Upper Arlington OH', 'aesthetic clinic Upper Arlington', 39.994400, -83.062500, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Shaker Heights OH', 'Cleveland', 'US', 'Midwest', 2, 'medspa Shaker Heights', 'medical spa Shaker Heights', 'aesthetic clinic Shaker Heights', 41.473900, -81.537300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Edina MN', 'Minneapolis', 'US', 'Midwest', 2, 'medspa Edina', 'medical spa Edina MN', 'aesthetic clinic Edina', 44.889700, -93.349900, 2);

-- ═══════════════════════════════════════════════════════════
-- US — WEST (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Cherry Creek Denver', 'Denver', 'US', 'West', 1, 'medspa Cherry Creek Denver', 'medical spa Cherry Creek', 'aesthetic clinic Cherry Creek', 39.717400, -104.952800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Aspen', 'Aspen', 'US', 'West', 1, 'medspa Aspen', 'medical spa Aspen', 'aesthetic clinic Aspen', 39.191100, -106.817500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Boulder', 'Boulder', 'US', 'West', 2, 'medspa Boulder', 'medical spa Boulder CO', 'aesthetic clinic Boulder', 40.015000, -105.270500, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Park City UT', 'Park City', 'US', 'West', 1, 'medspa Park City', 'medical spa Park City Utah', 'aesthetic clinic Park City', 40.646100, -111.498000, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Bellevue WA', 'Seattle', 'US', 'West', 1, 'medspa Bellevue WA', 'medical spa Bellevue', 'aesthetic clinic Bellevue Washington', 47.610100, -122.201500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Mercer Island WA', 'Seattle', 'US', 'West', 2, 'medspa Mercer Island', 'medical spa Mercer Island', 'aesthetic clinic Mercer Island', 47.570700, -122.222100, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Lake Oswego OR', 'Portland', 'US', 'West', 2, 'medspa Lake Oswego', 'medical spa Lake Oswego', 'aesthetic clinic Lake Oswego', 45.420700, -122.670600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Henderson NV', 'Las Vegas', 'US', 'West', 2, 'medspa Henderson NV', 'medical spa Henderson', 'aesthetic clinic Henderson Nevada', 36.039500, -114.981700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Summerlin NV', 'Las Vegas', 'US', 'West', 2, 'medspa Summerlin', 'medical spa Summerlin', 'aesthetic clinic Summerlin Las Vegas', 36.167300, -115.328400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Kahala Honolulu', 'Honolulu', 'US', 'West', 1, 'medspa Kahala', 'medical spa Honolulu', 'aesthetic clinic Kahala Honolulu', 21.269900, -157.777000, 1);

-- ═══════════════════════════════════════════════════════════
-- CANADA — ONTARIO (15)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Yorkville Toronto', 'Toronto', 'CA', 'Ontario', 1, 'medspa Yorkville Toronto', 'medical spa Yorkville', 'aesthetic clinic Yorkville Toronto', 43.670900, -79.393500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Forest Hill Toronto', 'Toronto', 'CA', 'Ontario', 1, 'medspa Forest Hill Toronto', 'medical spa Forest Hill', 'aesthetic clinic Forest Hill Toronto', 43.688100, -79.412600, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Rosedale Toronto', 'Toronto', 'CA', 'Ontario', 1, 'medspa Rosedale Toronto', 'medical spa Rosedale', 'aesthetic clinic Rosedale Toronto', 43.678300, -79.377900, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Bridle Path Toronto', 'Toronto', 'CA', 'Ontario', 1, 'medspa Bridle Path Toronto', 'medical spa Bridle Path', 'aesthetic clinic Bridle Path', 43.733300, -79.363700, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Oakville', 'Oakville', 'CA', 'Ontario', 2, 'medspa Oakville', 'medical spa Oakville', 'aesthetic clinic Oakville', 43.467500, -79.687700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('King City', 'King City', 'CA', 'Ontario', 2, 'medspa King City', 'medical spa King City', 'aesthetic clinic King City Ontario', 43.920800, -79.527200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Burlington', 'Burlington', 'CA', 'Ontario', 2, 'medspa Burlington Ontario', 'medical spa Burlington', 'aesthetic clinic Burlington Ontario', 43.325500, -79.799000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Port Credit Mississauga', 'Mississauga', 'CA', 'Ontario', 2, 'medspa Port Credit', 'medical spa Mississauga', 'aesthetic clinic Port Credit', 43.547600, -79.587100, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Rockcliffe Park Ottawa', 'Ottawa', 'CA', 'Ontario', 1, 'medspa Rockcliffe Park', 'medical spa Ottawa', 'aesthetic clinic Rockcliffe Ottawa', 45.447600, -75.674800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Westboro Ottawa', 'Ottawa', 'CA', 'Ontario', 2, 'medspa Westboro Ottawa', 'medical spa Westboro', 'aesthetic clinic Westboro Ottawa', 45.387500, -75.734400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Niagara-on-the-Lake', 'Niagara-on-the-Lake', 'CA', 'Ontario', 2, 'medspa Niagara-on-the-Lake', 'medical spa Niagara', 'aesthetic clinic Niagara-on-the-Lake', 43.254900, -79.071500, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Byron London ON', 'London', 'CA', 'Ontario', 2, 'medspa Byron London Ontario', 'medical spa London Ontario', 'aesthetic clinic London Ontario', 42.965400, -81.296700, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Sydenham Kingston', 'Kingston', 'CA', 'Ontario', 2, 'medspa Kingston Ontario', 'medical spa Kingston', 'aesthetic clinic Kingston Ontario', 44.233600, -76.481300, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Waterloo', 'Waterloo', 'CA', 'Ontario', 2, 'medspa Waterloo Ontario', 'medical spa Waterloo', 'aesthetic clinic Waterloo Ontario', 43.464300, -80.520400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Ancaster Hamilton', 'Hamilton', 'CA', 'Ontario', 2, 'medspa Ancaster', 'medical spa Hamilton Ontario', 'aesthetic clinic Ancaster', 43.217500, -79.987000, 2);

-- ═══════════════════════════════════════════════════════════
-- CANADA — BRITISH COLUMBIA (10)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('West Vancouver', 'Vancouver', 'CA', 'British Columbia', 1, 'medspa West Vancouver', 'medical spa West Vancouver', 'aesthetic clinic West Vancouver', 49.328000, -123.159600, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('North Vancouver', 'Vancouver', 'CA', 'British Columbia', 2, 'medspa North Vancouver', 'medical spa North Vancouver', 'aesthetic clinic North Vancouver', 49.320000, -123.072400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Kitsilano Vancouver', 'Vancouver', 'CA', 'British Columbia', 2, 'medspa Kitsilano', 'medical spa Kitsilano Vancouver', 'aesthetic clinic Kitsilano', 49.266700, -123.164600, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Yaletown Vancouver', 'Vancouver', 'CA', 'British Columbia', 1, 'medspa Yaletown', 'medical spa Yaletown Vancouver', 'aesthetic clinic Yaletown', 49.274500, -123.120800, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Kerrisdale Vancouver', 'Vancouver', 'CA', 'British Columbia', 2, 'medspa Kerrisdale', 'medical spa Kerrisdale Vancouver', 'aesthetic clinic Kerrisdale', 49.232900, -123.156800, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('White Rock', 'White Rock', 'CA', 'British Columbia', 2, 'medspa White Rock', 'medical spa White Rock BC', 'aesthetic clinic White Rock', 49.025300, -122.802800, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Oak Bay Victoria', 'Victoria', 'CA', 'British Columbia', 2, 'medspa Oak Bay Victoria', 'medical spa Victoria BC', 'aesthetic clinic Oak Bay', 48.426500, -123.314900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Kelowna', 'Kelowna', 'CA', 'British Columbia', 2, 'medspa Kelowna', 'medical spa Kelowna', 'aesthetic clinic Kelowna', 49.888000, -119.496000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Whistler', 'Whistler', 'CA', 'British Columbia', 2, 'medspa Whistler', 'medical spa Whistler', 'aesthetic clinic Whistler', 50.116300, -122.957400, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Tsawwassen', 'Tsawwassen', 'CA', 'British Columbia', 2, 'medspa Tsawwassen', 'medical spa Tsawwassen', 'aesthetic clinic Tsawwassen', 49.007400, -123.082800, 2);

-- ═══════════════════════════════════════════════════════════
-- CANADA — ALBERTA (8)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Mount Royal Calgary', 'Calgary', 'CA', 'Alberta', 1, 'medspa Mount Royal Calgary', 'medical spa Calgary', 'aesthetic clinic Mount Royal Calgary', 51.033000, -114.088700, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Elbow Park Calgary', 'Calgary', 'CA', 'Alberta', 1, 'medspa Elbow Park', 'medical spa Elbow Park Calgary', 'aesthetic clinic Elbow Park', 51.025300, -114.074500, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Aspen Woods Calgary', 'Calgary', 'CA', 'Alberta', 2, 'medspa Aspen Woods Calgary', 'medical spa Aspen Woods', 'aesthetic clinic Aspen Woods Calgary', 51.039100, -114.170900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Windermere Edmonton', 'Edmonton', 'CA', 'Alberta', 2, 'medspa Windermere Edmonton', 'medical spa Edmonton', 'aesthetic clinic Windermere Edmonton', 53.451600, -113.551000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Glenora Edmonton', 'Edmonton', 'CA', 'Alberta', 2, 'medspa Glenora Edmonton', 'medical spa Glenora', 'aesthetic clinic Glenora Edmonton', 53.544300, -113.536800, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Canmore', 'Canmore', 'CA', 'Alberta', 2, 'medspa Canmore', 'medical spa Canmore', 'aesthetic clinic Canmore', 51.088400, -115.357900, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Banff', 'Banff', 'CA', 'Alberta', 2, 'medspa Banff', 'medical spa Banff', 'aesthetic clinic Banff', 51.178400, -115.570800, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Cochrane', 'Cochrane', 'CA', 'Alberta', 2, 'medspa Cochrane Alberta', 'medical spa Cochrane', 'aesthetic clinic Cochrane Alberta', 51.189500, -114.467300, 2);

-- ═══════════════════════════════════════════════════════════
-- CANADA — QUEBEC + ATLANTIC (7)
-- ═══════════════════════════════════════════════════════════
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Westmount Montreal', 'Montreal', 'CA', 'Quebec', 1, 'medspa Westmount Montreal', 'medical spa Westmount', 'aesthetic clinic Westmount', 45.483300, -73.596300, 1);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Outremont Montreal', 'Montreal', 'CA', 'Quebec', 2, 'medspa Outremont', 'medical spa Outremont Montreal', 'aesthetic clinic Outremont', 45.521500, -73.602200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Old Montreal', 'Montreal', 'CA', 'Quebec', 2, 'medspa Old Montreal', 'medical spa Old Montreal', 'aesthetic clinic Old Montreal', 45.504800, -73.554200, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Mont-Tremblant', 'Mont-Tremblant', 'CA', 'Quebec', 2, 'medspa Mont-Tremblant', 'medical spa Mont-Tremblant', 'aesthetic clinic Mont-Tremblant', 46.209100, -74.585000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Sillery Quebec City', 'Quebec City', 'CA', 'Quebec', 2, 'medspa Sillery Quebec', 'medical spa Quebec City', 'aesthetic clinic Sillery', 46.772300, -71.245100, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('South End Halifax', 'Halifax', 'CA', 'Atlantic', 2, 'medspa South End Halifax', 'medical spa Halifax', 'aesthetic clinic Halifax', 44.636500, -63.578000, 2);
INSERT INTO public.affluent_areas (area_name, city, country, region, affluent_tier, search_term_1, search_term_2, search_term_3, latitude, longitude, scan_priority) VALUES ('Churchill Park St Johns', 'St Johns', 'CA', 'Atlantic', 2, 'medspa St Johns NL', 'medical spa St Johns Newfoundland', 'aesthetic clinic St Johns', 47.557400, -52.738700, 2);
